---
title: "PondSplit"
author: "Dylan Titmuss"
date: "2023-09-21"
output: html_document
editor_options: 
  chunk_output_type: console
---

First run chunks 2-6 of `PondShiny.Rmd` script.

# Identify surface data

```{r}
setwd("~/Desktop/Repos/CapeCodPonds2023")

pondName <- unique(ponds$Station.name)

focal_ponds <- ponds %>%
  filter(Month == 8 | Month == 9)

allSurface <- data.frame()

# determine other parameter outliers @ surface
for(pond in pondName) {
  onePond <- focal_ponds %>%
    select(-Pond.number) %>%
    filter(Station.name == pond) %>%
    # temporarily deal with NA depths
    filter(!is.na(Depth)) %>%
    # deal with replicate year samples
    group_by(Station.name, Lens, SizeClass, DepthClass, BufferClass, PercentBuffer,
             Year, Depth) %>%
    summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE))) %>%
    mutate(across(everything(), ~ replace_na(.x, NA)))
  
  if(nrow(onePond) == 0) {
    next
  }
  
  param_start <- which(colnames(onePond) == "Secchi")
  discrete_start <- which(colnames(onePond) == "DO_sat") + 1
  param_end <- which(colnames(onePond) == "Chla")
  
  oneSurface <- data.frame()
  
  for(year in unique(onePond$Year)) {
    for(j in 1:nrow(onePond[onePond$Year == year, ])) {
      depth = sort(onePond$Depth[onePond$Year == year])[j]
      if(j == nrow(onePond[onePond$Year == year, ])) {
        depth = sort(onePond$Depth[onePond$Year == year])[1]
        break
      }
      if(is.na(onePond$Temp[onePond$Year == year & onePond$Depth == depth])) {
        onePond$Temp[onePond$Year == year & onePond$Depth == depth] <-
          onePond$Temp[onePond$Year == year &
                          onePond$Depth == sort(onePond$Depth[onePond$Year == year])[j + 1]]
      }
      if(is.na(onePond$DO[onePond$Year == year & onePond$Depth == depth])) {
        onePond$DO[onePond$Year == year & onePond$Depth == depth] <-
          onePond$DO[onePond$Year == year &
                        onePond$Depth == sort(onePond$Depth[onePond$Year == year])[j + 1]]
      }
      if(!is.na(onePond$Temp[onePond$Year == year & onePond$Depth == depth]) &
         !is.na(onePond$DO[onePond$Year == year & onePond$Depth == depth])) {
        for(k in discrete_start:param_end) {
          param <- colnames(onePond)[k]
          if(is.na(onePond[[param]][onePond$Year == year & onePond$Depth == depth])) {
            for(l in 1:(nrow(onePond[onePond$Year == year, ])-1)) {
              depth2 = sort(onePond$Depth[onePond$Year == year])[l]
              if(is.na(onePond[[param]][onePond$Year == year & onePond$Depth == depth2])) {
                next
              }
              if(depth2 <= 1) {
                onePond[[param]][onePond$Year == year & onePond$Depth == depth] <-
                  onePond[[param]][onePond$Year == year & onePond$Depth == depth2]
                break
              }
            }
          }
        }
        break
      }
    }
    if(depth <= 1) {
      oneSurface <- rbind(oneSurface, onePond[onePond$Year == year & onePond$Depth == depth, ])
    }
  }
  for(i in param_start:param_end) {
    param <- colnames(oneSurface)[i]
    flag_name <- paste0(param, "_flag")
    if(sum(!is.na(oneSurface[[param]])) != 0) {
      m <- mean(oneSurface[[param]], na.rm = TRUE)
      sd <- sd(oneSurface[[param]], na.rm = TRUE)
      sd <- ifelse(is.na(sd), 0, sd)
    }
    # outliers <- vector()
    for(j in 1:nrow(oneSurface)) {
      if(is.na(oneSurface[[param]][j])) {
        oneSurface[[flag_name]][j] <- 4
      } else if(oneSurface[[param]][j] >= m - 3*sd & oneSurface[[param]][j] <= m + 3*sd) {
        oneSurface[[flag_name]][j] <- 2
      } else {
        oneSurface[[flag_name]][j] <- 3
        # outliers <- c(outliers, oneSurface$Sampling.number[j])
      }
    }
    # if(length(outliers) > 0 & i != 10 & i!= 11) {   ### change here when cols change
    #   outlier_frame[[param]][sum(!is.na(outlier_frame[[param]])) + 1:length(outliers)] <- outliers
    # }
  }
  allSurface <- rbind(allSurface, oneSurface)
}

allSurface$Station.name[allSurface$Station.name == "MA-634-01 / Mashpee-Wakeby Pond"] <-
  "MA-634-01 / Mashpee Lake"
allSurface$Station.name[allSurface$Station.name == "MA-1039-01 / Mashpee-Wakeby Pond"] <-
  "MA-1039-01 / Wakeby Pond"

write.csv(allSurface, "data/AllPonds_Surface.csv", row.names = FALSE)

allBottom <- data.frame()

# determine other parameter outliers @ bottom
for(pond in pondName) {
  onePond <- focal_ponds %>%
    select(-Pond.number) %>%
    filter(Station.name == pond) %>%
    # temporarily deal with NA depths
    filter(!is.na(Depth)) %>%
    # deal with replicate year samples
    group_by(Station.name, Lens, SizeClass, DepthClass, BufferClass, PercentBuffer,
             Year, Depth) %>%
    summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE))) %>%
    mutate(across(everything(), ~ replace_na(.x, NA)))
  
  if(nrow(onePond) == 0) {
    next
  }
  
  param_start <- which(colnames(onePond) == "Secchi") + 1
  discrete_start <- which(colnames(onePond) == "DO_sat") + 1
  param_end <- which(colnames(onePond) == "Chla") - 1
  
  oneBottom <- data.frame()
  
  # temporary; covers ponds without depth in characteristics datasheet
  if(is.na(onePond$Final.Depth[1]) & !is.na(onePond$Total.Depth[1])) {
    onePond$Final.Depth <- max(onePond$Total.Depth, na.rm = TRUE)
  }
  
  # second half temporary; covers ponds with no total depth data
  if(onePond$Final.Depth[1] < 3 | is.na(onePond$Final.Depth[1])) {
    next
  }
  
  for(year in unique(onePond$Year)) {
    for(j in 1:nrow(onePond[onePond$Year == year, ])) {
      depth = sort(onePond$Depth[onePond$Year == year], decreasing = TRUE)[j]
      if(j == nrow(onePond[onePond$Year == year, ])) {
        depth = sort(onePond$Depth[onePond$Year == year], decreasing = TRUE)[1]
        break
      }
      if(!is.na(onePond$Temp[onePond$Year == year & onePond$Depth == depth]) &
         is.na(onePond$DO[onePond$Year == year & onePond$Depth == depth])) {
        for(k in 1:(nrow(onePond[onePond$Year == year, ]) - 1)) {
          if(!is.na(onePond$DO[onePond$Year == year & onePond$Depth == depth])) {
            break
          } else {
            onePond$DO[onePond$Year == year & onePond$Depth == depth] <-
              onePond$DO[onePond$Year == year &
                            onePond$Depth == sort(onePond$Depth[onePond$Year == year],
                                                  decreasing = TRUE)[k + 1]]
          }
        }
      }
      if(!is.na(onePond$DO[onePond$Year == year & onePond$Depth == depth]) &
         is.na(onePond$Temp[onePond$Year == year & onePond$Depth == depth])) {
        for(k in 1:(nrow(onePond[onePond$Year == year, ]) - 1)) {
          if(!is.na(onePond$Temp[onePond$Year == year & onePond$Depth == depth])) {
            break
          } else {
            onePond$Temp[onePond$Year == year & onePond$Depth == depth] <-
              onePond$Temp[onePond$Year == year &
                            onePond$Depth == sort(onePond$Depth[onePond$Year == year],
                                                  decreasing = TRUE)[k + 1]]
          }
        }
      }
      if(is.na(onePond$Temp[onePond$Year == year & onePond$Depth == depth])) {
        onePond$Temp[onePond$Year == year & onePond$Depth == depth] <-
          onePond$Temp[onePond$Year == year &
                          onePond$Depth == sort(onePond$Depth[onePond$Year == year],
                                              decreasing = TRUE)[j + 1]]
      }
      if(is.na(onePond$DO[onePond$Year == year & onePond$Depth == depth])) {
        onePond$DO[onePond$Year == year & onePond$Depth == depth] <-
          onePond$DO[onePond$Year == year &
                        onePond$Depth == sort(onePond$Depth[onePond$Year == year],
                                              decreasing = TRUE)[j + 1]]
      }
      if(!is.na(onePond$Temp[onePond$Year == year & onePond$Depth == depth]) &
         !is.na(onePond$DO[onePond$Year == year & onePond$Depth == depth])) {
        for(l in discrete_start:param_end) {
          param <- colnames(onePond)[l]
          if(is.na(onePond[[param]][onePond$Year == year & onePond$Depth == depth])) {
            for(m in 1:nrow(onePond[onePond$Year == year, ])) {
              depth2 = sort(onePond$Depth[onePond$Year == year],
                            decreasing = TRUE)[m]
              if(depth2 < 0.75 * mean(onePond$Final.Depth)) {
                break
              } else if(is.na(onePond[[param]][onePond$Year == year & onePond$Depth == depth2])) {
                next
              } else if(!is.na(onePond[[param]][onePond$Year == year & onePond$Depth == depth2])) {
                onePond[[param]][onePond$Year == year & onePond$Depth == depth] <-
                  onePond[[param]][onePond$Year == year & onePond$Depth == depth2]
                break
              }
            }
          }
        }
        break
      }
    }
    if(depth >= 0.75 * mean(onePond$Final.Depth)) {
      oneBottom <- rbind(oneBottom, onePond[onePond$Year == year & onePond$Depth == depth, ])
    }
  }
  if(nrow(oneBottom) == 0) {
    next
  } else {
    for(i in param_start:param_end) {
      param <- colnames(oneBottom)[i]
      flag_name <- paste0(param, "_flag")
      if(sum(!is.na(oneBottom[[param]])) != 0) {
        m <- mean(oneBottom[[param]], na.rm = TRUE)
        sd <- sd(oneBottom[[param]], na.rm = TRUE)
        sd <- ifelse(is.na(sd), 0, sd)
      }
      # outliers <- vector()
      for(j in 1:nrow(oneBottom)) {
        if(is.na(oneBottom[[param]][j])) {
          oneBottom[[flag_name]][j] <- 4
        } else if(oneBottom[[param]][j] >= m - 3*sd & oneBottom[[param]][j] <= m + 3*sd) {
          oneBottom[[flag_name]][j] <- 2
        } else {
          oneBottom[[flag_name]][j] <- 3
          # outliers <- c(outliers, oneBottom$Sampling.number[j])
        }
      }
      # if(length(outliers) > 0) {
      #   outlier_frame[[param]][sum(!is.na(outlier_frame[[param]])) + 1:length(outliers)] <- outliers
      # }
    }
  }
  allBottom <- rbind(allBottom, oneBottom)
}

allBottom$Station.name[allBottom$Station.name == "MA-634-01 / Mashpee-Wakeby Pond"] <-
  "MA-634-01 / Mashpee Lake"
allBottom$Station.name[allBottom$Station.name == "MA-1039-01 / Mashpee-Wakeby Pond"] <-
  "MA-1039-01 / Wakeby Pond"

write.csv(allBottom, "data/AllPonds_Bottom.csv", row.names = FALSE)
```






## Calculate outliers
```{r include = FALSE}
outlier_frame <- data.frame(matrix(ncol = 24-9, nrow = 500))
colnames(outlier_frame) <- colnames(ponds)[10:24]

outlier_frame[["pH"]][seq_along(which(ponds$pH > 14))] <- ponds$Sampling.number[which(ponds$pH > 14)]
ponds$pH[ponds$pH > 14] <- NA
outlier_frame[["Temp"]][seq_along(which(ponds$Temp > 35 | ponds$Temp < 5))] <-
  ponds$Sampling.number[which(ponds$Temp > 35 | ponds$Temp < 5)]
ponds$Temp[ponds$Temp == 207] <- 20.7
ponds$Temp[ponds$Temp < 5] <- NA

# determine total depth & Secchi depth outliers
for(pond in pondName) {
  onePond <- ponds %>%
    filter(Station.name == pond)
  for(param in colnames(onePond)[10:11]) {
    m <- mean(onePond[[param]], na.rm = TRUE)
    sd <- sd(onePond[[param]], na.rm = TRUE)
    sd <- ifelse(is.na(sd), 0, sd)
    flag_name <- paste0(param, "_flag")
    outliers <- vector()
    for(j in 1:nrow(onePond)) {
      if(is.na(onePond[[param]][j])) {
        onePond[[flag_name]][j] <- 4
      } else if(onePond[[param]][j] >= m - 3*sd & onePond[[param]][j] <= m + 3*sd) {
        onePond[[flag_name]][j] <- 2
      } else {
        onePond[[flag_name]][j] <- 3
        outliers <- c(outliers, onePond$Sampling.number[j])
      }
    }
    if(length(outliers) > 0) {
      outlier_frame[[param]][sum(!is.na(outlier_frame[[param]])) + 1:length(outliers)] <- outliers
    }
  }
}
```

## Write outlier frame
```{r}
outlier_frame <- outlier_frame %>%
  filter(rowSums(is.na(.)) != ncol(.)) %>%
  select(where(~!all(is.na(.x)))) %>%
  select(-TP_ugL)

write.csv(outlier_frame, "data/outliers.csv", row.names = FALSE)
```

## Identify instances of flipped temp & DO
```{r}
flip <- ponds$Sampling.number[which(ponds$Temp <= 15 & ponds$DO >= 15 & ponds$DO <= 30)]
flip <- sort(unique(flip))

perc_sat <- sort(unique(ponds$Sampling.number[which(ponds$DO >= 30)]))

same <- sort(unique(ponds$Sampling.number[which(ponds$Temp == ponds$DO)]))
```
