---
title: "BarnstablePonds"
author: "Dylan Titmuss"
date: "2023-07-27"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(pals)

setwd("~/Desktop/Repos/BarnstablePonds2023")
```

## Load data
```{r}
ponds_full <- read.csv("data/072523_CC_AllPonds_WQ.csv", header = TRUE) %>%
  
  # remove non-data rows
  filter(Station.name != "")
```

## Merge same-parameter columns & reorganize data frame
```{r}
ponds <- ponds_full %>%
  unite(DO, Dissolved.Oxygen...Reported...DO, Dissolved.Oxygen...Reported...DO.1, sep = "") %>%
  unite(Temp, Water.Temperature...TEMP, Water.Temperature...TEMP.1, sep = "") %>%
  unite(pH, pH...PH, pH...PH.1, sep = "") %>%
  unite(DO_sat, Dissolved.Oxygen.Saturation...Reported...DO_SAT,
        Dissolved.Oxygen.Saturation...Reported...DO_SAT.1, sep = "") %>%
  unite(Sal, Salinity...SAL, Salinity...SAL.1, sep = "") %>%
  
  # remove unneeded columns
  select(-Station.name, -Sample.number) %>%
  select(-Quality.code, -Quality.code.1, -Quality.code.2, -Quality.code.3, -Quality.code.4, -Quality.code.5,
         -Quality.code.6, -Quality.code.7, -Quality.code.8, -Quality.code.9, -Quality.code.10,
         -Quality.code.11, -Quality.code.12, -Quality.code.13, -Quality.code.14, -Quality.code.15,
         -Quality.code.16, -Quality.code.17, -Quality.code.18, -Quality.code.19, -Quality.code.20,
         -Quality.code.21, -Quality.code.22, -Quality.code.23, -Quality.code.24, -Quality.code.25) %>%
  
  # split long/lat coordinates
  separate_wider_delim(Long.lat.coordinates, " / ", names = c("Long", "Lat"), too_few = "align_start") %>%
  
  # rename columns with redundant headers
  rename(Chlorophyll = Chlorophyll...CHLA,
         Secchi = Secchi.Depth...SECCHI,
         TP = Total.Phosphorus...TP,
         TP_ugL = Total.Phosphorus...micrograms.per.liter...TP_ugL,
         TN = Total.Nitrogen...Reported...TN,
         CTI_TP = Carlson.Trophic.Index...Total.Phosphorus.based...CTI_TP,
         CTI_Chlorophyll = Carlson.Trophic.Index...Chlorophyll.a.based...CTI_CHLA,
         CTI_Secchi = Carlson.Trophic.Index...Secchi.Depth.Based...CTI_SD,
         Alkalinity = Alkalinity...ALK,
         ORP = Oxidation.Reduction.Potential...ORP,
         Phaeophytin = Phaeophytin...PHAEO,
         Wind = Qualitative.Wind.Description...WIND,
         Conductivity = Specific.Conductivity...COND,
         Total.Dissolved.Solids = Total.Dissolved.Solids...TDS,
         Total.Pigments = Total.Pigments...TOTAL_PIGMENTS) %>%
  
  # reorder columns
  relocate(Temp, .before = DO) %>%
  relocate(DO_sat, .after = DO) %>%
  relocate(pH, .after = DO_sat) %>%
  relocate(Alkalinity, .after = pH) %>%
  relocate(Chlorophyll, .after = TN) %>%
  relocate(Phaeophytin, .after = Chlorophyll) %>%
  relocate(Total.Pigments, .after = Phaeophytin) %>%
  relocate(Sal, .before = Wind) %>%
  relocate(c(ORP, Conductivity), .after = last_col()) %>%
  
  # extract date from date-time column & create new column
  mutate(Date = str_extract(Date.Time..sampling., "\\d+/\\d+/\\d+"),
         Time = str_extract(Date.Time..sampling., "\\d{1,2}:\\d{2}")) %>%
  
  # extract month and year from date-time column & create new column
  mutate(Month = str_extract(Date.Time..sampling., "\\d{1,2}(?=/)"),
         Year = paste("20", str_extract(Date.Time..sampling., "(?<=\\d{1,2}/\\d{1,2}/)\\d+"), sep = ""))

# convert all empty cells to NA
ponds[ponds == ""] <- NA

# convert null datapoints to NA
ponds[ponds == "n.m. 0.00"] <- NA
ponds[ponds == "ND 0.00"] <- NA
ponds[ponds == "<MDL 0.00"] <- NA

# temporarily fix non-numeric datapoints
ponds[ponds == "> 15.50"] <- "15.50"
ponds[ponds == "< 0.05"] <- "0.05"
ponds[ponds == "< 1.50"] <- "1.50"
ponds[ponds == "< 0.10"] <- "0.10"
ponds[ponds == "207"] <- "20.7"

# temporarily remove problematic row
ponds <- ponds[-12083, ]

# convert all numerical cols to numeric
is_all_numeric <- function(x) {
  !any(is.na(suppressWarnings(as.numeric(na.omit(x))))) & is.character(x)
}
ponds <- ponds %>% 
  mutate_if(is_all_numeric, as.numeric)

#str(ponds)
```

## Summarize data
```{r}
count(ponds, Station.number) # 221 ponds
# min(count(ponds, Station.number)$n)
# max(count(ponds, Station.number)$n) # 1-420 observations per pond
# median(count(ponds, Station.number)$n) # median of 57 observations per pond
# 
# hist(count(ponds, Station.number)$n, breaks = 20, main = "Observations per pond")

pond_years <- ponds %>%
  group_by(Station.number, Lat, Long) %>%
  summarise(num_years = n_distinct(Year))

min(pond_years$num_years)
max(pond_years$num_years) # 1-18 total years of data
median(pond_years$num_years) # median of 10 years per pond

hist(pond_years$num_years, breaks = 20, main = "Years of data per pond")

pond_dates <- ponds %>%
  group_by(Station.number, Lat, Long, Year) %>%
  summarize(num_dates = n_distinct(Date))

min(pond_dates$num_dates)
max(pond_dates$num_dates) # 1-5 days sampled per year
median(pond_dates$num_dates) # median of 1 day sampled per year

hist(pond_dates$num_dates, breaks = 20, main = "Days sampled per year")

# pond_months
hist(ponds$Month, main = "Month of sampling event")

pond_profiles <- ponds %>%
  group_by(Station.number, Lat, Long, Year, Date) %>%
  summarise(num_depths = n_distinct(Depth)) %>%
  mutate(Profiles = ifelse(num_depths > 2, TRUE, FALSE))

hist(pond_profiles$num_depths, main = "Number of depths per sampling event")

nrow(filter(pond_profiles, num_depths > 2)) # 1910 sampling events w/ > 2 depths (1910 / 2215 = 86%)

pond_profiles2 <- pond_profiles %>%
  group_by(Station.number, Lat, Long) %>%
  summarise(num_dates = n_distinct(Date),
            num_years = n_distinct(Year),
            num_profiles = sum(Profiles)) %>%
  mutate(Years = ifelse(num_years > 1, TRUE, FALSE),
         Profiles = ifelse(num_profiles > 0, TRUE, FALSE))

pond_profiles3 <- ponds %>%
  group_by(Station.number, Lat, Long, Year, Date) %>%
  summarise(num_depths = n_distinct(Depth)) %>%
  group_by(Station.number, Lat, Long, Year) %>%
  summarise(num_depths = max(num_depths)) %>%
  mutate(Profiles = ifelse(num_depths > 2, TRUE, FALSE)) %>%
  group_by(Station.number, Lat, Long) %>%
  summarise(num_years = n_distinct(Year),
            num_years_profiles = sum(Profiles))
```

## Map ponds
```{r}
# identify GPS limits
min(ponds$Long, na.rm = TRUE) # -70.64806
max(ponds$Long, na.rm = TRUE) # -69.95501
min(ponds$Lat, na.rm = TRUE) # 41.55522
max(ponds$Lat, na.rm = TRUE) # 42.06855

# turn off spherical geometry to avoid "duplicate" errors
sf_use_s2(FALSE)

# get Massachusetts outline
mass <- read_sf("/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp") %>%
  st_make_valid() %>%
  st_crop(xmin = -71, xmax = -69, ymin = 41, ymax = 42.25)

# create a true/false map of multiple years
ggplot() +
  geom_sf(data = mass) +
  geom_point(data = pond_profiles2, aes(x = Long, y = Lat, col = Years)) +
  scale_color_discrete(name = ">1 year?") +
  xlim(-70.65, -69.95) +
  ylim(41.55, 42.07) +
  theme_bw() +
  theme(axis.title = element_blank())

# create a true/false map of profiles
ggplot() +
  geom_sf(data = mass) +
  geom_point(data = pond_profiles2, aes(x = Long, y = Lat, col = Profiles)) +
  scale_color_discrete(name = "profiles?") +
  xlim(-70.65, -69.95) +
  ylim(41.55, 42.07) +
  theme_bw() +
  theme(axis.title = element_blank())

# create map of years sampled
ggplot() +
  geom_sf(data = mass) +
  geom_point(data = pond_years, aes(x = Long, y = Lat, col = num_years)) +
  scale_color_gradientn(colors = parula(100)) +
  xlim(-70.65, -69.95) +
  ylim(41.55, 42.07) +
  theme_bw() +
  theme(axis.title = element_blank())

# create map of number of profiles
ggplot() +
  geom_sf(data = mass) +
  geom_point(data = pond_profiles2, aes(x = Long, y = Lat, col = num_profiles)) +
  scale_color_gradientn(colors = parula(100), name = "num_total_\nprofiles") +
  xlim(-70.65, -69.95) +
  ylim(41.55, 42.07) +
  theme_bw() +
  theme(axis.title = element_blank())

# create map of number of years of profiles
ggplot() +
  geom_sf(data = mass) +
  geom_point(data = pond_profiles3, aes(x = Long, y = Lat, col = num_years_profiles)) +
  scale_color_gradientn(colors = parula(100), name = "num_years\n_profiles") +
  xlim(-70.65, -69.95) +
  ylim(41.55, 42.07) +
  theme_bw() +
  theme(axis.title = element_blank())
```

## Create summary table
```{r}
# filter out months other than Aug & Sept
ponds <- ponds %>%
  filter(Month == 8 | Month == 9)

# column 1: pond ID
# column 2: pond name
# column 3: most recent year measured
# column 4: years of data
# column 5: years of profiles
# column 6: all years sampled
# column 7: all parameters measured
# column 8: years of each parameter
# column 9: most recent avg of each parameter @ discrete sampling depth

# column 1
pondID <- unique(ponds$Station.number)

# column 2
pond_name <- c()

for(i in 1:length(pondID)) {
  pond_name[i] <- ponds$Site[ponds$Station.number == pondID[i]][1]
}

# column 3
last_year <- c()

for(i in 1:length(pondID)) {
  last_year[i] <- max(ponds$Year[ponds$Station.number == pondID[i]])
}

# column 4
years_data <- c()

for(i in 1:length(pondID)) {
  years_data[i] <- n_distinct(ponds$Year[ponds$Station.number == pondID[i]])
}

# column 5
years_profiles <- c()

ponds_temp <- ponds %>%
  group_by(Station.number, Year, Date) %>%
  summarise(num_depths = n_distinct(Depth)) %>%
  group_by(Station.number, Year) %>%
  summarise(num_depths = max(num_depths)) %>%
  mutate(Profiles = ifelse(num_depths > 2, TRUE, FALSE)) %>%
  group_by(Station.number) %>%
  summarise(num_years_profiles = sum(Profiles))

for(i in 1:length(pondID)) {
  years_profiles[i] <- ponds_temp$num_years_profiles[ponds_temp$Station.number == pondID[i]]
}

# column 6
all_years <- c()

for(i in 1:length(pondID)) {
  string <- c()
  for(j in 1:n_distinct(ponds$Year[ponds$Station.number == pondID[i]])) {
    year <- unique(ponds$Year[ponds$Station.number == pondID[i]])[j]
    if(is.null(string)) {
      string <- year
    } else {
      string <- paste(string, year, sep = ", ")
    }
  }
  all_years[i] <- string
}

# column 7
params <- c()

for(i in 1:length(pondID)) {
  temp_frame <- ponds[ponds$Station.number == pondID[i], ]
  string <- c()
  for(j in 9:(ncol(temp_frame) - 4)) {
    if(sum(!is.na(temp_frame[j])) > 0) {
      if(is.null(string)) {
        string = colnames(temp_frame)[j]
      } else {
        string = paste(string, colnames(temp_frame)[j], sep = ", ")
      }
    }
  }
  params[i] <- string
}

# column 8
param_years <- c()

for(i in 1:length(pondID)) {
  temp_frame <- ponds[ponds$Station.number == pondID[i], ]
  string <- c()
  p_list <- str_split(params[i], ", ")[[1]]
  for(j in 1:length(p_list)) {
    colname = p_list[j]
    if(sum(!is.na(temp_frame[[paste0(colname)]])) > 0) {
      if(is.null(string)) {
        string = n_distinct(temp_frame$Year[!is.na(temp_frame[[paste0(colname)]])])
      } else {
        string = paste(string, n_distinct(temp_frame$Year[!is.na(temp_frame[[paste0(colname)]])]), sep = ", ")
      }
    }
  }
  param_years[i] <- string
}

# column 9
surface_depths <- ponds %>%
  group_by(Station.number, Year) %>%
  summarise(min_depth = min(Depth))

# use 1m as cutoff for "surface" measurements?

# temporarily deal with NA depths
ponds$Depth[is.na(ponds$Depth) & ponds$Station.number != "DE-281-01"] <- 0.5

surface <- as.data.frame(c())

for(i in 1:length(pondID)) {
  temp_frame <- ponds[ponds$Station.number == pondID[i], ] %>%
    # temporarily deal with NA depths
    filter(!is.na(Depth)) %>%
    # deal with replicate rows
    group_by(Station.number, Year, Depth) %>%
    summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE))) %>%
    mutate(across(everything(), ~ replace_na(.x, NA)))
  for(j in 1:length(unique(temp_frame$Year))) {
    year = unique(temp_frame$Year)[j]
    for(k in 1:nrow(temp_frame[temp_frame$Year == year, ])) {
      depth = sort(temp_frame$Depth[temp_frame$Year == year])[k]
      if(nrow(temp_frame[temp_frame$Year == year, ]) == 1) {
        break
      }
      if(k == nrow(temp_frame[temp_frame$Year == year, ])) {
        depth = sort(temp_frame$Depth[temp_frame$Year == year])[1]
      }
      if(!is.na(temp_frame$Total.Depth...DTB[temp_frame$Year == year & temp_frame$Depth == depth]) &
         is.na(temp_frame$Temp[temp_frame$Year == year & temp_frame$Depth == depth])) {
        temp_frame$Temp[temp_frame$Year == year & temp_frame$Depth == depth] <-
          temp_frame$Temp[temp_frame$Year == year &
                          temp_frame$Depth == sort(temp_frame$Depth[temp_frame$Year == year])[k + 1]]
      }
      if(!is.na(temp_frame$Total.Depth...DTB[temp_frame$Year == year & temp_frame$Depth == depth]) &
         is.na(temp_frame$DO[temp_frame$Year == year & temp_frame$Depth == depth])) {
        temp_frame$DO[temp_frame$Year == year & temp_frame$Depth == depth] <-
          temp_frame$DO[temp_frame$Year == year &
                        temp_frame$Depth == sort(temp_frame$Depth[temp_frame$Year == year])[k + 1]]
      }
      if(!is.na(temp_frame$Total.Depth...DTB[temp_frame$Year == year & temp_frame$Depth == depth]) &
         !is.na(temp_frame$Temp[temp_frame$Year == year & temp_frame$Depth == depth])) {
        break
      }
    }
    surface <- rbind(surface, temp_frame[temp_frame$Year == year & temp_frame$Depth == depth, ])
  }
}

param_last_values <- c()

for(i in 1:length(pondID)) {
  temp_frame <- surface[surface$Station.number == pondID[i], ]
  string <- c()
  y_list <- str_split(all_years[i], ", ")[[1]]
  p_list <- str_split(params[i], ", ")[[1]]
  for(j in 1:length(p_list)) {
    colname = p_list[j]
    if(sum(!is.na(temp_frame[[paste0(colname)]])) == 0) {
      val <- NA
    } else {
      for(k in 1:length(y_list)) {
        val <- round(temp_frame[[paste0(colname)]][temp_frame$Year == tail(y_list, k)[1]], 2)
        if(!is.na(val)) {
          break
        }
      }
    }
    if(is.null(string)) {
      string = val
    } else {
      string = paste(string, val, sep = ", ")
    }
  }
  param_last_values[i] <- string
}

# create data frame
pond_summary <- as.data.frame(cbind(pondID, pond_name, years_data, years_profiles,
                      params, param_years, last_year, param_last_values)) %>%
  mutate_if(is_all_numeric, as.numeric)
```

## Create depth plots
```{r}
ggplot(surface[(surface$Station.number == "BA-411-01" & !is.na(surface$Secchi)), ], aes(x = Year, y = Secchi, group = Station.number)) +
  geom_line() +
  scale_y_reverse() +
  #scale_color_gradientn(colors = parula(100)) +
  theme_bw()

# ggplot(surface[!is.na(surface$Secchi), ], aes(x = Year, y = Secchi, group = Station.number)) +
#   geom_line() +
#   scale_y_reverse() +
#   theme_bw()

ggplot(ponds, aes(x = Temp, y = Depth, group = interaction(Station.number, Year), col = Year)) +
  geom_line() +
  scale_y_reverse() +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(ponds, aes(x = DO, y = Depth, group = interaction(Station.number, Year), col = Year)) +
  geom_line() +
  scale_y_reverse() +
  xlim(0, 25) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(ponds, aes(x = pH, y = Depth, group = interaction(Station.number, Year), col = Year)) +
  geom_line() +
  scale_y_reverse() +
  xlim(3, 10) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(ponds, aes(x = Alkalinity, y = Depth, group = interaction(Station.number, Year), col = Year)) +
  geom_line() +
  scale_y_reverse() +
  xlim(0, 200) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(ponds, aes(x = TP, y = Depth, group = interaction(Station.number, Year), col = Year)) +
  geom_line() +
  scale_y_reverse() +
  xlim(0, 75) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(ponds, aes(x = TN, y = Depth, group = interaction(Station.number, Year), col = Year)) +
  geom_line() +
  scale_y_reverse() +
  xlim(0, 450) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(ponds, aes(x = Chlorophyll, y = Depth, group = interaction(Station.number, Year), col = Year)) +
  geom_line() +
  scale_y_reverse() +
  xlim(0, 300) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()
```

## Create property-property plots
```{r}
ggplot(surface, aes(x = TP, y = TN, col = Year)) +
  geom_point() +
  xlim(0, 14) +
  ylim(0, 280) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(surface, aes(x = Chlorophyll, y = TP, col = Year)) +
  geom_point() +
  ylim(0, 14) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()

ggplot(surface, aes(x = Chlorophyll, y = TN, col = Year)) +
  geom_point() +
  #geom_smooth(se = FALSE) +
  ylim(0, 280) +
  scale_color_gradientn(colors = parula(100)) +
  theme_bw()
```



## Create prelim visualizations of data presence/absence
```{r}
# ponds_filt <- ponds %>%
#   group_by(Station.number) %>%
#   filter(n_distinct(Year) >= 10) %>%
#   ungroup()

ponds1 <- ponds %>%
  filter(Station.number <= "CH-396-01")
ponds2 <- ponds %>%
  filter(Station.number > "CH-396-01" & Station.number <= "MA-808-01")
ponds3 <- ponds %>%
  filter(Station.number > "MA-808-01")

# Temp
ggplot(ponds1, aes(Year, Temp)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Temp)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Temp)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)

# DO
ggplot(ponds1, aes(Year, DO)) +
  geom_point() +
  ylim(0, 20) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, DO)) +
  ylim(0, 20) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, DO)) +
  ylim(0, 20) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)

# Chl-a
ggplot(ponds1, aes(Year, Chlorophyll...CHLA)) +
  geom_point() +
  ylim(0, 50) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Chlorophyll...CHLA)) +
  ylim(0, 50) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Chlorophyll...CHLA)) +
  ylim(0, 50) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)

# Secchi
ggplot(ponds1, aes(Year, Secchi.Depth...SECCHI)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Secchi.Depth...SECCHI)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Secchi.Depth...SECCHI)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)

# TP
ggplot(ponds1, aes(Year, Total.Phosphorus...TP)) +
  geom_point() +
  ylim(0, 15) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Total.Phosphorus...TP)) +
  geom_point() +
  ylim(0, 15) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Total.Phosphorus...TP)) +
  geom_point() +
  ylim(0, 15) +
  facet_wrap(~ Station.number, ncol = 9)

# TN
ggplot(ponds1, aes(Year, Total.Nitrogen...Reported...TN)) +
  geom_point() +
  ylim(0, 100) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Total.Nitrogen...Reported...TN)) +
  geom_point() +
  ylim(0, 100) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Total.Nitrogen...Reported...TN)) +
  geom_point() +
  ylim(0, 100) +
  facet_wrap(~ Station.number, ncol = 9)

# Alk
ggplot(ponds1, aes(Year, Alkalinity...ALK)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Alkalinity...ALK)) +
  geom_point() +
  ylim(0, 200) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Alkalinity...ALK)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)

# pH
ggplot(ponds1, aes(Year, pH)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, pH)) +
  geom_point() +
  ylim(0, 10) +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, pH)) +
  geom_point() +
  ylim(0, 10) +
  facet_wrap(~ Station.number, ncol = 9)

# Sal
ggplot(ponds1, aes(Year, Sal)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Sal)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Sal)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)

# Phaeophytin
ggplot(ponds1, aes(Year, Phaeophytin...PHAEO)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Phaeophytin...PHAEO)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Phaeophytin...PHAEO)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)

# Total Pigments
ggplot(ponds1, aes(Year, Total.Pigments...TOTAL_PIGMENTS)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds2, aes(Year, Total.Pigments...TOTAL_PIGMENTS)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 8)
ggplot(ponds3, aes(Year, Total.Pigments...TOTAL_PIGMENTS)) +
  geom_point() +
  facet_wrap(~ Station.number, ncol = 9)
```
